name = "nipo-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Replace the ID below with your actual KV ID after creating it on Cloudflare.
# command: npx wrangler kv:namespace create "NIPO_KV"
kv_namespaces = [
  { binding = "NIPO_KV", id = "3f48a38d5a40497f837d953487a59bbd" }
]

[vars]
API_SECRET = "nipo-secret"
